name: CI/CD
on:
  pull_request:
    branches: [ master ]
    types: [opened, synchronize, reopened, edited, closed]
  push:
    branches: [ master, test_linter_version ]

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Super-Linter
        uses: Neha-Sinha2305/super-linter@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ANSIBLE: true
          VALIDATE_BASH: true
          VALIDATE_DOCKER_HADOLINT: true
          VALIDATE_GO: true
          VALIDATE_HTML: true
          VALIDATE_JAVA: true
          VALIDATE_JSON: true
          VALIDATE_MD: true
          VALIDATE_OPENAPI: true
          VALIDATE_PYTHON: true
          VALIDATE_PYTHON_PYLINT: true
          VALIDATE_PYTHON_FLAKE8: true
          VALIDATE_RUBY: true
          VALIDATE_SQL: true
          VALIDATE_TERRAFORM: true
          VALIDATE_XML: true
